language: java
jdk:
- oraclejdk8

#deploy:
#- provider: s3
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#  file: jar/server.jar
#  local_dir: dpl_cd_upload
#  skip_cleanup: true
#  on: master
#  repo: cormaclavery/TCIIT
#  bucket: cormac-test-bucket-ci
#  region: eu-central-1
#- provider: codedeploy
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#  bucket: cormac-test-bucket-ci
#  key: latest.zip
#  bundle_type: zip
#  application: TestApp2
#  deployment_group: TestDeploymentGroup2
#  region: eu-central-1
#  on: master

script:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip