version: 0.0
os: linux
files:
  - source: /jar/
    destination: /home/ubuntu/jar
  - source: /deploy-scripts/
    destination: /home/ununtu/deploy-scripts

hooks:
  AfterInstall:
  - location: deploy-scripts/after-deploy.sh
    timeout: 120
    runas: root